### ISSUE TITLE
Invalid Magnet URI Scheme from `/download`

### ISSUE THREAD

**Issue by silktrader** [ahandre94/tnt_village#1]
Using Telegram's bot (web interface), and qBittorrent (v4.3.2), `/download whatever` will produce a Magnet link of the sort:

`magnet:/?xt=urn:btih:8450432F1E3B28745B051AEED9A0F264366XXXXX&dn=File+Name.torrent`

qBittorrent though doesn't recognise the URI scheme and throws an error. Removing the forward slash "/" fixes the issue.

Looking around, it seems the slash is unnecessary: https://metacpan.org/pod/URI::magnet

**Comment by silktrader** [comment]
(thanks for the bot, by the way)

**Comment by ahandre94** [comment]
Thanks for the tip. I solved the problem with the new deploy
